version: "3"
services:
  nginx:
    ports:
      - "5000:80"
  express-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/portfolio
      - /portfolio/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=Bader
      - MONGO_PASSWORD=myPassword
      - SESSION_SECRET=someSecret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bader
      - MONGO_INITDB_ROOT_PASSWORD=myPassword