version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./server/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./view/pages/404.html:/etc/nginx/conf.d/404.html:ro
      - ./view:/usr/share/nginx/html
  express-app:
    build: .
    image: baderidris/portfolio
    environment:
      - PORT=5000
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    # try installing new versions, on prod servers! needs newer CPUs than mine
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Bader
      - MONGO_INITDB_ROOT_PASSWORD=myPassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    volumes:
      - ./server/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      # - ./server/redis/.overcommit_memory:/proc/sys/vm/overcommit_memory
    # command:
      # - sh -c "echo 1 > /proc/sys/vm/overcommit_memory"
      # - ./redis-server /usr/local/etc/redis/redis.conf
      # - redis-server AUTH default myPassword
      # - AUTH default myPassword
volumes:
  mongo-db: